services:
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: projectnessie/nessie:latest
    container_name: catalog
    networks:
      dremio-university:
    ports:
      - 19120:19120

  # Minio Storage Server
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      dremio-university:
    ports:
      - 9001:9001
      - 9000:9000
    entrypoint: >
      /bin/sh -c "
      echo 'Starting MinIO server...' &&
      minio server /data --console-address :9001 &

      echo 'Waiting for MinIO to start...' &&
      until curl --silent --fail http://minio:9000/minio/health/live; do sleep 2; done &&
      
      echo 'MinIO is running, configuring...' &&
      mc alias set local http://minio:9000 admin password &&
      if ! mc ls local/warehouse > /dev/null 2>&1; then mc mb local/warehouse; fi &&
      echo 'Bucket created.'
      && tail -f /dev/null"

  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    container_name: dremio
    networks:
      dremio-university:
networks:
  dremio-university: